"""init

Revision ID: 67d5955ff50c
Revises: 
Create Date: 2026-03-14 02:31:44.777894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d5955ff50c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.UUID(), server_default=sa.text('(uuid())'), nullable=False),
    sa.Column('transaction_type', sa.INTEGER(), nullable=False),
    sa.Column('data', sa.TEXT(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('sign', sa.String(length=64), nullable=False),
    sa.Column('signer_cert', sa.String(length=512), nullable=False),
    sa.Column('transaction_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.TEXT(), nullable=True),
    sa.Column('transaction_in', sa.String(length=64), nullable=True),
    sa.Column('transaction_out', sa.String(length=64), nullable=True),
    sa.Column('message_receiver_batch', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_message_receiver_batch'), 'transaction', ['message_receiver_batch'], unique=False)
    op.create_index(op.f('ix_transaction_transaction_time'), 'transaction', ['transaction_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_transaction_time'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_message_receiver_batch'), table_name='transaction')
    op.drop_table('transaction')
    # ### end Alembic commands ###
